services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=taskapp'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
    networks:
      - taskapp
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=postgres@email.com'
      - 'PGADMIN_DEFAULT_PASSWORD=postgres'
    ports:
      - '5050:80'
    networks:
      - taskapp
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
networks:
  taskapp:
    driver: bridge
volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local

